### ISSUE TITLE
request: Flutter_Riverpod  integration

### ISSUE THREAD

**Issue by cccarv** [VeryGoodOpenSource/very_good_cli#109]
**Description**
Is there anyway to use the great **Very Good CLI** to create a project using Riverpod? 

**Expected Behavior**
Structure created with riverpod.

**Comment by jorgecoca** [comment]
Hi @cccarv 👋 

Thank you so much for your request. At this moment, `very_good_cli` is an opinionated project generated that uses tools that the team at Very Good Ventures is familiar with. Riverpod, as of now, is not part of those tools, and that's why I can say with confidence that we do not foresee adding Riverpod in the short term future, and instead, we will continue investing in the structure created with `flutter_bloc`.

Thank you!

**Comment by jeremiahlukus** [comment]
@cccarv I have done that here:
https://github.com/jeremiahlukus/flutter_template  

Im going to make branches with other features this one will probably be moved to basic_template 

I modified a few things and added stuff but for the most part its a clone of a very_good_cli
