### ISSUE TITLE
fix: runs command twice in windows

### ISSUE THREAD

**Issue by saileshbro** [VeryGoodOpenSource/very_good_cli#121]
**Description**
very_good command is run twice in windows.

**Steps To Reproduce**

1. Go to terminal and push `very_good`

**Expected Behavior**
It is expected for the command to run only once.

**Screenshots**
![image](https://user-images.githubusercontent.com/43571990/114340588-9e0d0900-9b77-11eb-9532-f0d7118b4a1c.png)

**Additional Context**
Maybe this is the error with dart itself, I found the same [issue ](https://github.com/leoafarias/fvm/issues/227) with fvm too.
You can see the dart issue [here](https://github.com/dart-lang/pub/issues/2934).

**Comment by felangel** [comment]
Hi @saileshbro 👋 
Thanks for opening an issue!

As you mentioned, I believe this is not specific to `very_good_cli` and is a broader issue with `pub`. Closing this since it is being tracked by https://github.com/dart-lang/pub/issues/2934 and I don't believe there is anything that can be done by `very_good_cli`. 👍
