### ISSUE TITLE
fix: Creating a project named "test" breaks bloc dependencies

### ISSUE THREAD

**Issue by S0NN1** [VeryGoodOpenSource/very_good_cli#182]
**Description**
Creating a project with the package name "test":
```console
C:\Users\Sonny>very_good create test
```
 breaks the `flutter pub get` command and exits the command in an error state.

**Steps To Reproduce**

1. Install very_good_cli.
2. Run very_good create test.
3. See error.

**Expected Behavior**
The program should print the following warning:
```console
"test" is not a valid package name.

See https://dart.dev/tools/pub/pubspec#name for more information.

🦄 A Very Good Command Line Interface

Usage: very_good <command> [arguments]

Global options:
-h, --help           Print this usage information.
    --version        Print the current version.
    --analytics      Toggle anonymous usage statistics.

          [false]    Disable anonymous usage statistics
          [true]     Enable anonymous usage statistics

Available commands:
  create   very_good create <output directory>
           Creates a new very good project in the specified directory.

Run "very_good help <command>" for more information about a command.
```

**Screenshots**
![ApplicationFrameHost_WKrppZuVHp](https://user-images.githubusercontent.com/40118754/133702497-e445fed1-de2c-45db-bdff-29254c0cc61f.png)

**Additional Context**
Tried also on WSL(Windows Subsystem for Linux) and got the same results.

**Comment by felangel** [comment]
Hi @S0NN1 👋 
Thanks for opening an issue!

This isn't specific to very_good_cli -- the same thing would happen if you ran `flutter create test`. This is because `test` is already a real package and you can't have the current project have the same name as an existing dependency. You should rename your project to avoid conflicts by re-running `very_good create example_test` or something other than `test` and everything should work as expected.

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation.
