### ISSUE TITLE
question: Copyright comments in generated code

### ISSUE THREAD

**Issue by Prn-Ice** [VeryGoodOpenSource/very_good_cli#210]
**Description**
Is it okay to delete the copyright comments from the generated code?

**Comment by felangel** [comment]
Hi @Prn-Ice 👋 
Thanks for opening an issue!

It’s not okay to remove the copyright header. You may modify or use the code provided that the copyright notice and License shall be included in all copies or substantial portions of the Software.

Hope that helps 👍

**Comment by Prn-Ice** [comment]
Ok so I leave the copyright headers.
I'm allowed to delete the generated license right?, I'm building a commercial app and its an MIT license.

**Comment by nikkijuk** [comment]
@Prn-Ice https://brainhub.eu/library/open-source-licenses-to-avoid

MIT license is good for libraries generally, in generated code I'm not certain how it affects projects. All projects created using vgv cli core template have generated artifacts with MIT license, and this has spinned questions in my organization. 

I understand concerns: if copyleft license in generated code might pollute complete project so that all the code in project we develop can be interpreted as open source our management won't just allow us to use vgv core. 

https://www.zdnet.com/article/ipad-black-friday-deals-november-23-2022/

When code is created for blocs there's no license, which is to me simple way  to go with generated code.

https://github.com/felangel/bloc/blob/master/bricks/bloc/__brick__/%7B%7B%7E%20freezed_bloc%20%7D%7D

@felangel I would have liked generated vgv core to have no license at all or apache license. Then I wouldn't need to get deep on discussions of risks and fears that OSS licenses can have in worst case.

**Comment by felangel** [comment]
@nikkijuk we've updated the very_good_cli and all of our open source templates to exclude licenses and copyright headers for all generated code. Feel free to remove any copyright headers or licenses from previously generated code -- we apologize for any inconvenience!

We're working on improving the documentation around this to hopefully eliminate any confusion moving forward. Hope that helps and let us know if you have any other questions/concerns, thanks! 💙

**Comment by nikkijuk** [comment]
Thanks @felangel. I'm glad that this was possible and I really value tremendous job you are doing to get whole community ahead.
