### ISSUE TITLE
feat: Make `very_good packages get` recursive by default

### ISSUE THREAD

**Issue by definitelyokay** [VeryGoodOpenSource/very_good_cli#251]
I think running `very_good packages get` should be recursive by default, since we could just run `flutter pub get` or `dart pub get` if we wanted to get the packages for the project in the current directory.

Even shortening the command would be welcome, if possible: `very_good get`

**Comment by felangel** [comment]
Hi @definitelyokay 👋 
Thanks for opening an issue!

I think we should create a separate issue to discuss renaming the command if you feel strongly about it.

Regarding running recursively by default, the thinking behind the current behavior was to mirror how `flutter packages get` works with the added ability to perform the install recursively if you'd like.

The main disadvantages of making recursive the default imo are:

- We're making the default behavior the heavier/slower behavior
  - This makes sense if we assume developers only use `very_good packages get` when they want the recursive functionality and then rely on `flutter packages get` and `dart pub get` for normal installations but as I mention below the original goal was to have a single command that works for all scenarios rather than having to constantly think about which command to use.
- If a developer does only want to run the command for the current package the command would be: `very_good packages get --no-recursive`
  - this is a lot more painful and we'd definitely encourage developers to switch between `very_good packages get` and `flutter packages get`/`dart pub get` depending on their use case. The goal was not to have to think about which command to use and instead have a single command that does the right thing.

At the end of the day I think it boils down to do developers prefer to use `very_good packages get` for everything or do they prefer to only use `very_good packages get` for the recursive install while switching back to `dart pub get` and `flutter packages get` for non-recursive installs. I know I personally would like to just use one command since it's one less thing to worry about but I realize this is subjective and am curious to hear your thoughts as well as other feedback from the team/community.

**Comment by definitelyokay** [comment]
I don't feel strongly about any this, I just think about it briefly whenever I use `very_good packages get -r`. 

> We're making the default behavior the heavier/slower behavior

True, but I am quite aware as a developer when I am working on a plain Dart project vs a Flutter project, so knowing to use `dart pub get` and `flutter pub get` has never been a struggle. Obviously, I would only turn to a non-official Flutter tool if the Flutter one couldn't do it. I.e., the cli tool is an augmentation to the Flutter tooling that has the ability to generate better packages, not a replacement for the Flutter CLI. At least, philosophically, that is how I've always viewed it. Now, having a tool that can intelligently run either package command might be moderately useful for CI/CD purposes, but I hadn't thought about that being a goal for VG CLI.

> If a developer does only want to run the command for the current package the command would be: very_good packages get --no-recursive

Do we have automated use cases where we need a tool to intelligently know which package command to run? If we do, that is something that could be broken out into a separate tool (or something, I'm just ideating). Or is this simply developer preference?

**Comment by felangel** [comment]
> I don't feel strongly about any this, I just think about it briefly whenever I use `very_good packages get -r`.
> 
> > We're making the default behavior the heavier/slower behavior
> 
> True, but I am quite aware as a developer when I am working on a plain Dart project vs a Flutter project, so knowing to use `dart pub get` and `flutter pub get` has never been a struggle. Obviously, I would only turn to a non-official Flutter tool if the Flutter one couldn't do it. I.e., the cli tool is an augmentation to the Flutter tooling that has the ability to generate better packages, not a replacement for the Flutter CLI. At least, philosophically, that is how I've always viewed it. Now, having a tool that can intelligently run either package command might be moderately useful for CI/CD purposes, but I hadn't thought about that being a goal for VG CLI.
> 
> > If a developer does only want to run the command for the current package the command would be: very_good packages get --no-recursive
> 
> Do we have automated use cases where we need a tool to intelligently know which package command to run? If we do, that is something that could be broken out into a separate tool (or something, I'm just ideating). Or is this simply developer preference?

We do have automated cases where we run `very_good packages get -r` at the root of a project to automatically install dependencies in the root flutter application workflow.

**Comment by definitelyokay** [comment]
> We do have automated cases where we run very_good packages get -r at the root of a project to automatically install dependencies in the root flutter application workflow.

Do you have automated cases where you *don't* run it recursively?

**Comment by felangel** [comment]
> > We do have automated cases where we run very_good packages get -r at the root of a project to automatically install dependencies in the root flutter application workflow.
> 
> Do you have automated cases where you _don't_ run it recursively?

Not that I'm aware of. To be clear, I am fine with making recursive the default -- what I am trying to understand is whether we want to support non-recursive installation via the cli or not. If so, what will that look like?

**Comment by felangel** [comment]
> Given that we are considering supporting running tests in a package (which might also recursively run tests), I think we can close this.

Sounds good!
