### ISSUE TITLE
feat: update CLI before command execution

### ISSUE THREAD

**Issue by achamorro-dev** [VeryGoodOpenSource/very_good_cli#355]
**Description**
When you execute a command, for example `very_good create`, and you have an outdated version of the CLI you get an alert to update after the commands are executed. It would be great if this alert appears before to use the last version in this execution.

**Screenshots**
<img width="665" alt="image" src="https://user-images.githubusercontent.com/1499378/161600350-c7bb4b86-337a-460b-8dc6-a27407210a6f.png">

**Comment by wolfenrain** [comment]
For context, the update prompt was changed in v0.6.0, it no longer asks if you want to update because developers/companies often want to just pin the CLI to a version and update it when they want. Prompting users about an update they don't want (yet) would be a bit annoying 😅.

We now only tell people that there is an update and how they can update the CLI themselves:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/15887627/162421021-2a88dfb2-8f45-4f02-83d6-783401a0790f.png">

Showing this at the start of a command would probably be problematic as the command is already doing "things". 

But we are of course open to suggestions on how to improve the update-cycle!

**Comment by achamorro-dev** [comment]
Thanks for your response! I think that it’s a good approach 😋

**Comment by felangel** [comment]
Closing for now then since it seems like there are no actionable steps needed. Feel free to comment with any follow-up questions and I'm happy to continue the conversation 👍
