### ISSUE TITLE
fix: shouldn't we commit the `pubspec.lock` because it's an application package? 

### ISSUE THREAD

**Issue by nilsreichardt** [VeryGoodOpenSource/very_good_cli#423]
**Description**
Isn't this package an application package? If yes, I think we should also commit the `pubspec.lock` (recommended by Dart: https://dart.dev/guides/libraries/private-files#pubspeclock)

**Comment by felangel** [comment]
Hi @nilsreichardt 👋 
Thanks for opening an issue!

I believe in this case we shouldn't because when a CLI app is installed it'll resolve the latest possible dependency constraints so we want to always be developing against the latest possible versions. You can also refer to [pana](https://github.com/dart-lang/pana) (another Dart CLI maintained by the Dart team).

Let me know if that helps 👍

**Comment by nilsreichardt** [comment]
Yeah, makes sense. Also, when `pana` is doing this I think is also good to follow this pattern 👍
