### ISSUE TITLE
fix: update very_good update command suggest to update again

### ISSUE THREAD

**Issue by cgutierr-zgz** [VeryGoodOpenSource/very_good_cli#472]
**Description**
After running `very_good update` you still get prompted to update

**Steps To Reproduce**

1. Run `very_good update`
2. You will see

```sh
✓ Checked for updates (x.xs)
✓ Updated to 0.x.x (x.xs)

Update available! x.x.xx → x.x.xx+1
Changelog: https://github.com/verygoodopensource/very_good_cli/releases/tag/vx.x.xx+1
Run very_good update to update
```

3. Run `very_good update` again
4. You will see it's already up to date anyway
`Very Good CLI is already at the latest version.`

**Expected Behavior**
When I run `very_good update` and it updates it I shouldn't receive this prompt to update again

**Screenshots**
![Screenshot 2022-07-28 at 11 29 18](https://user-images.githubusercontent.com/18635739/181476878-d5c6105e-e832-43dd-92e2-e03d21f75b13.png)

**Comment by felangel** [comment]
Hi @cgutierr-zgz 👋 
Thanks for opening an issue!

We're aware of this issue and hope to resolve it soon. This is most likely due to having an incompatible version of Dart/Flutter so the update silently fails. Please make sure to update to the latest stable version of Dart/Flutter and try again.

Thanks for your patience and sorry for the inconvenience.

**Comment by cgutierr-zgz** [comment]
@felangel 
Thanks for the reply
Both dart and flutter are one the latest stable version so idk

Anyway is not a problem for me, thanks!

**Comment by renancaraujo** [comment]
Clsoed on #523
