### ISSUE TITLE
feat: support `--no-pub` flag on `very_good test`

### ISSUE THREAD

**Issue by felangel** [VeryGoodOpenSource/very_good_cli#504]
As a developer, I want to be able to run tests offline just like when using `flutter test`.

**Comment by BeatriceMitchell** [comment]
When work starts on this, we can check to see what flags are supported here vs. on VG Tooling

**Comment by erickzanardo** [comment]
We discussed internally and the cli forces the `no-pub` flag on test executions in favor of time optimisation, since most of the times, developers only want to run the tests as the dependencies were already installed previously.

Usually, you would only install the dependencies before running the tests in a fresh clone, but even so it would be more performant if `pub get` were run once on all packages of the project recursively. Something that is already accounted for on `very_good_workflows`.

So given those reasons, we opt to not implement such flag on very good cli, in other to do a fresh dependencies install before running your tests, be sure to run `very_good packages get` before.
