### ISSUE TITLE
feat: add support to run codegen command recursively

### ISSUE THREAD

**Issue by mugbug** [VeryGoodOpenSource/very_good_cli#509]
## Description

Since `very_good_cli` already enables running some core flutter commands in a recursive way (i.e. `packages get` & `test`), it seems reasonable to me to add a `build_runner` command to it as well, reusing the recursive execution feature.

## Proposal

Add a `very_good build_runner` command, which could proxy the default `build_runner` command and add a new `-r; --recursive` flag to run it to all packages recursively.

**Comment by felangel** [comment]
Hi @mugbug 👋 
Thanks for opening an issue!

The difference here imo is that `build_runner` is not part of the core toolchain (it's a separate dependency that is not built into the flutter/dart core toolchain).

I personally would prefer not to extend very_good_cli's scope beyond core flutter/dart toolchain but would love to hear what others think.

**Comment by erickzanardo** [comment]
Maybe instead of specifically implementing something for build runner, we could provide a very_hood pub run -r? Which would then just proxy whatever the user runs?

That way I think we solve @mugbug request but also keep the tool inside the core flutter features like @felangel advocates, which I also agree haha

**Comment by felangel** [comment]
After discussing this we've decided to close this as "won't fix" because:

- codegen is something that isn't native to flutter/dart tooling (it requires an additional dependency)
- it isn't clear how we'd want to handle partial successes (`build_runner` failed for one package but not the others)
- it would be straightforward to write a generic bash script to run any arbitrary command recursively so the value of including this functionality in `very_good_cli` is minimal.

Sorry for the inconvenience!
