### ISSUE TITLE
fix: Running the cli with --ios false still generates ios directory.

### ISSUE THREAD

**Issue by munsterlander** [VeryGoodOpenSource/very_good_cli#575]
**Description**
Running the cli with --ios false still generates ios directory.

**Steps To Reproduce**
As simple as the description.  Just create a new template for flame_game with --ios false and the directory is still generated.  The other ones are honored though as --macos false did not create the directory.

**Expected Behavior**
When specifying a platform flag as false, the directory should not be created, nor should it be mentioned in the readme.

**Comment by wolfenrain** [comment]
Hi! These flags (`--ios`, `--android`, `--macos`, etc..) are only used for the `flutter_plugin` template, so they dont work for all the other templates like `flame_game` and `very_good_core`.

The reason that it looked like `macOS` was honoured is because we don't support macOS for our app templates 😅. Hope that clear it up for you.

We are refactoring our `create` command in #490 so that each template will be it's own command and we wont have this confusion about the flags!

Will close this issue as it we will handle this in #490
