### ISSUE TITLE
feat(create)! subcommand: Very Good Flutter Project Usage

### ISSUE THREAD

**Issue by Yczar** [VeryGoodOpenSource/very_good_cli#601]
I want to work on this feature that supports other state management patterns like Riverpod and Provider. 

This allows users to create projects with other preferred state management patterns but still supports Bloc by default.

# Very Good Flutter Project Usage
very_good create <project-name> <options>

options:
    --arch

**Comment by felangel** [comment]
Hi @Yczar 👋 
Thanks for opening an issue!

Our templates are VGV-opinionated but feel free to [create your own mason templates](https://docs.brickhub.dev) or use [existing templates from the community](https://brickhub.dev/search) to fit your needs!

Closing for now since this isn't within the scope of the Very Good CLI, hope that helps! 👍
