### ISSUE TITLE
fix: very_good test doesn't like [ in file names

### ISSUE THREAD

**Issue by KyleFin** [VeryGoodOpenSource/very_good_cli#648]
**Description**
very_good test fails when files have [] in their filenames (as seen in [Dart Frog dynamic route](https://dartfrog.vgv.dev/docs/basics/routes#dynamic-routes-) files).

**Steps To Reproduce**

**Expected Behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/5882840/217967175-32e2d9c7-d448-478d-8eff-431a0eecfd57.png)

**Additional Context**

**Comment by BeatriceMitchell** [comment]
Given that this is a P1 (highest priority), anyone taking this must be ready to respond to feedback quickly to make sure it gets pushed.

**Comment by alestiago** [comment]
I was not able to reproduce the error under latest version (0.11.0+1) not (0.10.0) with the following minimal [sample](https://github.com/alestiago/issues/tree/main/very_good_cli__648).

@KyleFin do you have a minimal sample that reproduces this error?

**Comment by alestiago** [comment]
Reproduced issue with [minimal sample code](https://github.com/alestiago/issues/tree/main/very_good_cli/648) under version `0.11.0+1` .

**Comment by alestiago** [comment]
@KyleFin the issue seems to be within the optimisation process. In the meantime you can use:

```sh
very_good test --no-optimization
```

I've looked into [`very_good_test_runner`](https://github.com/VeryGoodOpenSource/very_good_test_runner) which runs the flutter test command `_flutterTest` and the test succeeds when there is are `[` and `]` characters in the name.  Although the optimisation step shows to be completing successfully its generation dislikes the fact that a test file has `[` or `]` characters in test file names.
