### ISSUE TITLE
how to generate Java rather than Kotlin

### ISSUE THREAD

**Issue by osamamohammed98** [VeryGoodOpenSource/very_good_cli#678]
1. I am not fluent in Kotlin so I need to create my projects in Java

- it try this command and not work 
- very_good create flutter_app iistshir_user --i objc -a java  --desc "My new Flutter app" --application-id "com.XXXXXXXX"

**Comment by renancaraujo** [comment]
Hello there, the flutter_app template is an opinionated template based on the VGV standards. Even though we don't discourage people from using it, we cannot accommodate java support there for the following reason:
- Kotlin has been the default language for android flutter apps since [2019](https://github.com/flutter/flutter/pull/38339)
- Java as an android language on `flutter create` is documented as a legacy.
- [Android is Kotlin first since 2019](https://techcrunch.com/2019/05/07/kotlin-is-now-googles-preferred-language-for-android-app-development/).

For those reasons, we will not add support for java as android language for the "very good" templates. 

> it try this command and not work

Because options such as `-a` and `--i` are not used by `very_good create`. 
To see the available options, run:

```
very_good create flutter_app --help
```
