### ISSUE TITLE
feat: Allow Creating Flavors for an existing Flutter App

### ISSUE THREAD

**Issue by rivella50** [VeryGoodOpenSource/very_good_cli#849]
**Description**
I would like to be able to add flavors _after_ i have created a Flutter app, i.e. that i'm independent of having to create a new Flutter app.
Not just once i had the situation that i started a Flutter mobile app where it was clear only later that different flavors would be necessary (or the customer decided it later and told me to integrate them).

**Expected Behavior**
As an addition to #680 there should be at least one additional subcommand (e.g. 'flavors') which performs the same steps as in 'create' but only regarding the creation/integration of flavors.

**Comment by tomarra** [comment]
Hi @rivella50 👋 Thanks for the ticket on this. Currently none of the commands in `very_good_cli` work as a modification to an existing codebase. The focus for the tool is really around getting something started with a good base to work from. We have investigated ways to do these kinds of modifications in the past but with codebases looking so different project to project we haven't found a fully automated way to make it succeed in way that we think is acceptable. Given that we are continuing the focus on making sure this is the best tool for starting a project rather than modifying it.

Given that this won't be given a priority I'm closing this out as a "won't fix".

**Comment by rivella50** [comment]
Hi Tom,

ok, that's understandable. Thanks for your explanation.
