### ISSUE TITLE
feat: Suggestion to add flag to generate firebase setup for each flavor

### ISSUE THREAD

**Issue by pauli2406** [VeryGoodOpenSource/very_good_cli#92]
**Description**
Based on my own projects it is often required to add firebase to a project. I often faced the issue that this can become quite complex when running different environments based on flavors. That is why it could be a nice addition to add this as a feature.

What do you think about it? If so I would take a look at it as soon as I find some free time.

**Comment by felangel** [comment]
Hi @pauli2406 👋 
Thanks for opening an issue!

At this time, we welcome bug tickets but will not be accepting feature requests because the roadmap and scope of this project is still being defined. In addition, we understand that Very Good Core is basic and lacks many features that might be desirable in a starter application but this is a conscious decision made to keep the scope of Very Good Core focused to just foundational items. In the future, we may support additional, more feature-rich templates but at this time we would ask that issues be reserved for bugs only. Thanks! 💙
