### ISSUE TITLE
Is there anyway to pass the threshold to the Golden Test comparator?

### ISSUE THREAD

**Issue by jamontes79** [VeryGoodOpenSource/very_good_cli#972]
**Description**
I want to use a custom Golden Test comparator to use a threshold for comparing the generated images. Is that possible? Is there any documentation?

I've been searching in the closed issues and I've found some of them closed but nothing explaining how to use it.

Thanks in advance

**Comment by jamontes79** [comment]
Any news about this? Thanks

**Comment by alestiago** [comment]
Hi @jamontes79 , sorry for the late reply, I'll assign this to myself and will hopefully be able to provide documentation and clarity to the question.

**Comment by jamontes79** [comment]
> Hi @jamontes79 , sorry for the late reply, I'll assign this to myself and will hopefully be able to provide documentation and clarity to the question the upcoming week.

No worries. Thanks a lot!

**Comment by alestiago** [comment]
@jamontes79 you should be able to use the [`goldenFileComparator`](https://api.flutter.dev/flutter/flutter_test/goldenFileComparator.html) property in the `flutter_test` library to achieve so. There is no additional code that you'll need to provide to make it work with `very_good test`, since the optimized test already [consider and respect explicitly the `goldenFileComparator`](https://github.com/VeryGoodOpenSource/very_good_cli/blob/2824dceea61ef44393f52cf2ffbe35ba85d86589/bricks/test_optimizer/__brick__/test/.test_optimizer.dart#L13).

Here's an example on how a test with some tolerance would look like:

```dart
import 'dart:typed_data';

import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('renders as expected', (WidgetTester tester) async {
    final previousGoldenFileComparator = goldenFileComparator;
    goldenFileComparator = _TolerantGoldenFileComparator(
      // Replace with your test file path:
      Uri.parse('test/widget_test.dart'),
      precisionTolerance: 0.01,
    );
    addTearDown(() => goldenFileComparator = previousGoldenFileComparator);

    await tester.pumpWidget(
      const ColoredBox(
        color: Color(0xff00ff00),
        child: SizedBox.square(dimension: 100),
      ),
    );

    await expectLater(
      find.byType(ColoredBox),
      matchesGoldenFile('my_golden.png'),
    );
  });
}

class _TolerantGoldenFileComparator extends LocalFileComparator {
  _TolerantGoldenFileComparator(
    super.testFile, {
    required double precisionTolerance,
  }) : _precisionTolerance = precisionTolerance;

  /// How much the golden image can differ from the test image.
  ///
  /// It is expected to be between 0 and 1. Where 0 is no difference (the same image)
  /// and 1 is the maximum difference (completely different images).
  final double _precisionTolerance;

  @override
  Future<bool> compare(Uint8List imageBytes, Uri golden) async {
    final result = await GoldenFileComparator.compareLists(
      imageBytes,
      await getGoldenBytes(golden),
    );

    final passed = result.passed || result.diffPercent <= _precisionTolerance;
    if (passed) {
      result.dispose();
      return true;
    }

    final error = await generateFailureOutput(result, golden, basedir);
    result.dispose();
    throw FlutterError(error);
  }
}

```

Note that it is good practice to reset the value back to its original to avoid your comparator leaking into other golden tests when running parallelised tests. If you want to define a global configuration read into using the flutter_test_config.dart.

---

I've seen there's a lack of documentation online regarding this practice, hence I'll try to follow-up this item with documentation on our tooling (Very Good CLI), [Flutter documentation](https://github.com/flutter/flutter/issues/76337#issuecomment-795486138), and [Stack Overflow answers](https://stackoverflow.com/a/78510535/14335923).

**Comment by tomarra** [comment]
Waiting on https://github.com/flutter/flutter/pull/150422 to get reviewed/merged on this.
